post http://localhost:3000/login/
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}
### 8
get http://localhost:3000/tweets/4/replies/
authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzA2ODYxMzQyfQ.LGFfTuGJvcXpxZJz_GjwVjKahiip0XZ-YG-3oE_BaTE



### 9
get http://localhost:3000/user/tweets/
authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzA2ODYxMzQyfQ.LGFfTuGJvcXpxZJz_GjwVjKahiip0XZ-YG-3oE_BaTE

### 10
post http://localhost:3000/user/tweets/
authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzA2ODYxMzQyfQ.LGFfTuGJvcXpxZJz_GjwVjKahiip0XZ-YG-3oE_BaTE
Content-Type: application/json

{
   "tweet": "The Mornings..."
}

### 11
delete http://localhost:3000/tweets/2/
authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNzA2ODYxMzQyfQ.LGFfTuGJvcXpxZJz_GjwVjKahiip0XZ-YG-3oE_BaTE
